View segments in islandora
Islandora-Image-Segmentation/Islandora-Image-Segmentation-Solution-Pack pull request #12
Opened 2021-03-03 03:06 UTC by dynac01

Segments and newspapers are viewable in the image viewer.

2021-03-14 20:47 UTC, Alexander-Cairns requested changes
Looks great! Just remove the Vagrantfile from the gitignore.

2021-03-14 20:47 UTC, Alexander-Cairns commented on .gitignore
> +Vagrantfile
```suggestion
```
Vagrantfile should be tracked

2021-03-14 20:56 UTC, dynac01 commented
> Looks great! Just remove the Vagrantfile from the gitignore.

Done

2021-03-15 16:04 UTC, Alexander-Cairns approved these changes
Looks great will merge now

2021-03-15 16:05 UTC, merged