Create page with textfield
Islandora-Image-Segmentation/Islandora-Image-Segmentation-Solution-Pack pull request #9
Opened 2021-03-02 02:52 UTC by dynac01

Button not shows label and submit hook works as intended. Ready to implement Solr querying.

2021-03-02 18:26 UTC, Alexander-Cairns requested changes
Great work!

Instead of using `require_once` to include the form use the `'file'` field in the menu hook.

The form id should be changed to not use the term article.

2021-03-02 18:26 UTC, Alexander-Cairns commented on image_segmentation.module
> +      ),
```suggestion
        'file' => 'includes/manual_article_segmentation.form.inc',
      ),
```
You can use this instead of `require_once`

2021-03-02 18:26 UTC, Alexander-Cairns commented on image_segmentation.module
> +require_once dirname(__FILE__) . '/includes/manual_article_segmentation.form.inc';
```suggestion
```
Add the `'file'` filed instead in the menu hook.

2021-03-03 03:21 UTC, dynac01 commented
> Great work!
> 
> Instead of using `require_once` to include the form use the `'file'` field in the menu hook.
> 
> The form id should be changed to not use the term article.

All Implemented and pushed

2021-03-08 22:09 UTC, closed without merging